CREATE TABLE users (
  id serial PRIMARY KEY,
  email varchar(255) NOT NULL
);
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE users FORCE ROW LEVEL SECURITY;
CREATE TRIGGER users_audit_trg AFTER INSERT OR UPDATE OR DELETE ON users
  FOR EACH ROW EXECUTE FUNCTION audit_log();

CREATE TABLE orders (
  id bigserial PRIMARY KEY,
  user_id integer NOT NULL REFERENCES users(id)
);
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders FORCE ROW LEVEL SECURITY;
CREATE TRIGGER orders_audit_trg AFTER INSERT ON orders
  FOR EACH ROW EXECUTE FUNCTION audit_log();
